// This prototype stores history locally for demonstration purposes. In production this would be backed by a persistent database.

export interface DealHistoryItem {
  id: string;
  company_name: string;
  industry: string;
  country?: string;
  date_time: string;
  timestamp: number;
  funding_amount: number;
  risk_level: "Low" | "Medium" | "High";
  report_summary: string;
  full_report: any; // Complete deal data payload (input & report)
  export_status: "PDF/DOCX Available" | "Generated";
}

const STORAGE_KEY = "ai_deal_brief_history_v1";
const EVENT_NAME = "deal_history_updated";

// Default initial demo data so the prototype starts with rich visual content
const DEFAULT_INITIAL_DEALS: DealHistoryItem[] = [
  {
    id: "deal-demo-101",
    company_name: "TechFlow Solutions",
    industry: "SaaS",
    country: "USA",
    date_time: "Today, 2:30 PM",
    timestamp: Date.now() - 1000 * 60 * 90, // 1.5 hrs ago
    funding_amount: 15000000,
    risk_level: "Low",
    report_summary: "TechFlow Solutions demonstrates robust ARR growth of 42% YoY with zero customer churn in enterprise tiers. Recommended for Senior Bank Debt under favorable covenants.",
    export_status: "PDF/DOCX Available",
    full_report: {
      id: "deal-demo-101",
      status: "complete",
      input: {
        company_name: "TechFlow Solutions",
        industry: "SaaS",
        country: "USA",
        revenue: 15000000,
        ebitda: 4200000,
        employees: 85,
        funding_amount: 15000000,
        funding_purpose: "Global expansion & R&D for AI workflow agents",
        existing_debt: 1500000,
        years_in_business: 6,
        business_description: "Cloud-native workflow automation platform for financial service providers."
      },
      report: {
        ai_confidence_score: 0.94,
        executive_summary: "TechFlow Solutions demonstrates robust ARR growth of 42% YoY with zero customer churn in enterprise tiers. The company presents a low-risk debt profile with strong debt-service coverage ratio (DSCR > 2.8x). Recommended for Senior Bank Debt under favorable covenants.",
        company_overview: "Founded in 2020, TechFlow Solutions provides mission-critical enterprise software automating complex workflow orchestration for middle-market commercial lenders.",
        business_analysis: "B2B SaaS business model with high net revenue retention (124%). High switching costs and 3-year enterprise contracts provide long-term cash flow predictability.",
        industry_analysis: "Financial technology automation is expanding at a 22.4% CAGR through 2030, driven by legacy institution modernization demands.",
        financial_highlights: "Revenue: $15,000,000 | EBITDA: $4,200,000 | EBITDA Margin: 28% | Debt Service Coverage Ratio: 2.85x",
        funding_requirement: "Seeking $15,000,000 senior secured credit facility to accelerate international expansion and market acquisition.",
        financing_requirement: "Senior secured term loan amortized over 5 years with a 12-month interest-only grace period.",
        recommended_debt_structure: "5-Year Term Loan ($10M) + Revolving Line of Credit ($5M) at SOFR + 325 bps.",
        repayment_recommendation: "Quarterly principal repayments funded from operating cash flows, supported by high recurring revenue predictability.",
        loan_structure: "First-lien pledge on accounts receivable and intellectual property. Minimum DSCR covenant set at 1.35x.",
        recommended_lender_categories: [
          { category_name: "Senior Commercial Banks", likelihood_of_approval: "High", fit_explanation: "Strong cash flow & low leverage make this an ideal candidate for tier-1 commercial bank pricing." },
          { category_name: "Private Debt Funds", likelihood_of_approval: "High", fit_explanation: "Provides flexibility for potential additional growth capital accordion." }
        ],
        risk_assessment: "Low overall credit risk. Primary sensitivity involves execution risk in international sales channel expansion.",
        strengths: ["Strong EBITDA margins (>28%)", "High Net Revenue Retention (124%)", "Low Existing Leverage (0.35x Debt/EBITDA)"],
        potential_concerns: ["Sales cycle expansion in EMEA region", "Key person risk in core architecture team"],
        analyst_notes: "Strong management team with previous exits. Highly recommended for full approval.",
        sources: ["https://techcrunch.com", "SEC Filings", "Internal Financial Audit 2025"],
        disclaimer: "This report is generated by AI for preliminary review and does not constitute a final credit commitment."
      }
    }
  },
  {
    id: "deal-demo-102",
    company_name: "Apex Manufacturing",
    industry: "Industrials",
    country: "USA",
    date_time: "Yesterday, 4:15 PM",
    timestamp: Date.now() - 1000 * 60 * 60 * 26, // 26 hrs ago
    funding_amount: 45000000,
    risk_level: "Medium",
    report_summary: "Apex Manufacturing is seeking $45M for equipment automation and plant facility expansion. Asset coverage is strong (1.4x), though inventory turnover requires monitoring.",
    export_status: "PDF/DOCX Available",
    full_report: {
      id: "deal-demo-102",
      status: "complete",
      input: {
        company_name: "Apex Manufacturing",
        industry: "Industrials",
        country: "USA",
        revenue: 85000000,
        ebitda: 12500000,
        employees: 320,
        funding_amount: 45000000,
        funding_purpose: "Automated robotics machinery & facility expansion",
        existing_debt: 12000000,
        years_in_business: 14,
        business_description: "Precision component manufacturing for aerospace and automotive OEMs."
      },
      report: {
        ai_confidence_score: 0.88,
        executive_summary: "Apex Manufacturing is seeking $45M for equipment automation and plant facility expansion. Asset coverage is strong (1.4x tangible asset backing), though inventory turnover requires quarterly monitoring due to supply chain cycles.",
        company_overview: "Established precision manufacturer serving Tier-1 automotive and aerospace prime contractors with long-term Master Service Agreements.",
        business_analysis: "High capital intensity balanced by long-term customer lock-in and high barriers to entry.",
        industry_analysis: "Domestic re-shoring of advanced manufacturing is driving strong order backlogs across North American precision machining.",
        financial_highlights: "Revenue: $85,000,000 | EBITDA: $12,500,000 | EBITDA Margin: 14.7% | Debt/EBITDA: 0.96x",
        funding_requirement: "Equipment financing tranche ($30M) + Real estate expansion loan ($15M).",
        financing_requirement: "7-Year Asset-Backed Loan facility with monthly principal and interest payments.",
        recommended_debt_structure: "7-Year Senior Secured Equipment Loan at prime + 150 bps.",
        repayment_recommendation: "Monthly amortization backed by fixed revenue from 5-year OEM supplier contracts.",
        loan_structure: "First lien on all newly acquired robotics machinery and plant property.",
        recommended_lender_categories: [
          { category_name: "Asset-Based Lenders (ABL)", likelihood_of_approval: "High", fit_explanation: "Excellent hard asset collateral collateralization ratio." },
          { category_name: "Equipment Finance Specialist", likelihood_of_approval: "High", fit_explanation: "Competitive rates for specialized industrial machinery." }
        ],
        risk_assessment: "Medium risk due to cyclical automotive exposure, offset by strong machinery liquidation value.",
        strengths: ["14-year operational track record", "Tangible asset backing (1.4x coverage)", "Long-term OEM supplier agreements"],
        potential_concerns: ["Raw material steel price volatility", "Customer concentration (top 3 clients represent 55% revenue)"],
        analyst_notes: "Solid industrial play. Require quarterly inventory audits as a loan condition.",
        sources: ["Industry Manufacturing Report Q1 2026", "Company Audit 2025"],
        disclaimer: "This report is generated by AI for preliminary review."
      }
    }
  },
  {
    id: "deal-demo-103",
    company_name: "Nova Health Tech",
    industry: "Healthcare",
    country: "USA",
    date_time: "Jul 22, 2026",
    timestamp: Date.now() - 1000 * 60 * 60 * 72, // 3 days ago
    funding_amount: 120000000,
    risk_level: "High",
    report_summary: "Nova Health Tech is requesting $120M syndicated facility for diagnostic clinic acquisition. High leverage profile requires Mezzanine or Unitranche structure.",
    export_status: "PDF/DOCX Available",
    full_report: {
      id: "deal-demo-103",
      status: "complete",
      input: {
        company_name: "Nova Health Tech",
        industry: "Healthcare",
        country: "USA",
        revenue: 140000000,
        ebitda: 18000000,
        employees: 650,
        funding_amount: 120000000,
        funding_purpose: "Strategic acquisition of regional diagnostic clinic network",
        existing_debt: 45000000,
        years_in_business: 9,
        business_description: "Multi-site outpatient diagnostic imaging and healthcare analytics provider."
      },
      report: {
        ai_confidence_score: 0.81,
        executive_summary: "Nova Health Tech is requesting a $120M syndicated facility for diagnostic clinic acquisition. High total leverage (6.6x Debt/EBITDA post-deal) requires a Unitranche or Mezzanine capital structure with equity co-investment.",
        company_overview: "Rapidly growing outpatient healthcare services network across the Midwestern United States.",
        business_analysis: "Scalable hub-and-spoke model benefiting from shifting care trends toward outpatient centers.",
        industry_analysis: "Healthcare services remain resilient to economic downturns, supported by demographic tailwinds.",
        financial_highlights: "Revenue: $140,000,000 | EBITDA: $18,000,000 | Post-Deal Debt/EBITDA: 6.6x",
        funding_requirement: "$120,000,000 acquisition financing package.",
        financing_requirement: "Unitranche debt with equity sponsor contribution of at least 35%.",
        recommended_debt_structure: "Unitranche Facility ($90M) + Subordinated Debt ($30M).",
        repayment_recommendation: "Bullet maturity at 6 years with mandatory excess cash flow sweeps.",
        loan_structure: "Full pledge of equity in target acquisition entities + corporate guarantee.",
        recommended_lender_categories: [
          { category_name: "Healthcare Private Credit Funds", likelihood_of_approval: "Medium", fit_explanation: "Comfortable with higher leverage profiles in healthcare services." },
          { category_name: "Mezzanine Debt Providers", likelihood_of_approval: "High", fit_explanation: "Subordinated debt tranche provides necessary equity cushion." }
        ],
        risk_assessment: "High risk profile due to post-acquisition leverage and healthcare regulatory compliance.",
        strengths: ["Resilient healthcare sector demand", "Experienced clinical management", "Significant post-deal synergy potential ($4.5M)"],
        potential_concerns: ["High post-deal leverage (6.6x)", "Integration risk of acquired clinic network"],
        analyst_notes: "Require 35% equity contribution from sponsor before approving term sheet.",
        sources: ["Healthcare M&A Quarterly", "Medicare Reimbursement Tables"],
        disclaimer: "This report is generated by AI for preliminary review."
      }
    }
  }
];

export function getHistoryItems(): DealHistoryItem[] {
  if (typeof window === "undefined") return DEFAULT_INITIAL_DEALS;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      // Initialize with default demo items if clean state
      localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_INITIAL_DEALS));
      return DEFAULT_INITIAL_DEALS;
    }
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      return parsed;
    }
    return DEFAULT_INITIAL_DEALS;
  } catch (err) {
    console.error("Error reading deal history from localStorage:", err);
    return DEFAULT_INITIAL_DEALS;
  }
}

export function saveHistoryItem(deal: any): DealHistoryItem {
  const existing = getHistoryItems();
  
  // Extract fields safely from deal payload
  const input = deal.input || {};
  const report = deal.report || {};
  
  const id = deal.id || `deal-${Date.now()}`;
  const company_name = input.company_name || "Untitled Deal";
  const industry = input.industry || "General";
  const country = input.country || "";
  const funding_amount = Number(input.funding_amount) || 0;
  
  // Determine risk level based on report data or metrics
  let risk_level: "Low" | "Medium" | "High" = "Low";
  if (report.risk_level) {
    risk_level = report.risk_level;
  } else {
    const existingDebt = Number(input.existing_debt) || 0;
    const revenue = Number(input.revenue) || 1;
    const ebitda = Number(input.ebitda) || 1;
    const debtToRev = existingDebt / revenue;
    const leverage = (funding_amount + existingDebt) / Math.max(ebitda, 1);
    
    if (leverage > 5.5 || debtToRev > 0.45) {
      risk_level = "High";
    } else if (leverage > 3.2 || debtToRev > 0.25) {
      risk_level = "Medium";
    } else {
      risk_level = "Low";
    }
  }

  // First 2-3 lines of executive summary
  const summaryText = report.executive_summary || "AI-generated Enterprise Deal Brief with strategic recommendations and lender matching.";
  const report_summary = summaryText.length > 220 ? summaryText.slice(0, 220) + "..." : summaryText;

  const now = new Date();
  const date_time = now.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true
  });

  const newItem: DealHistoryItem = {
    id,
    company_name,
    industry,
    country,
    date_time,
    timestamp: Date.now(),
    funding_amount,
    risk_level,
    report_summary,
    full_report: deal,
    export_status: "PDF/DOCX Available"
  };

  // Check if item already exists and update, or prepend to front (Newest first)
  const filtered = existing.filter(item => item.id !== id);
  const updated = [newItem, ...filtered];

  if (typeof window !== "undefined") {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
      window.dispatchEvent(new CustomEvent(EVENT_NAME, { detail: updated }));
    } catch (err) {
      console.error("Error saving deal history to localStorage:", err);
    }
  }

  return newItem;
}

export function deleteHistoryItem(id: string): void {
  const existing = getHistoryItems();
  const updated = existing.filter(item => item.id !== id);
  
  if (typeof window !== "undefined") {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
      window.dispatchEvent(new CustomEvent(EVENT_NAME, { detail: updated }));
    } catch (err) {
      console.error("Error deleting deal history item:", err);
    }
  }
}

export function clearHistory(): void {
  if (typeof window !== "undefined") {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify([]));
      window.dispatchEvent(new CustomEvent(EVENT_NAME, { detail: [] }));
    } catch (err) {
      console.error("Error clearing deal history:", err);
    }
  }
}

export function subscribeHistoryUpdates(callback: (items: DealHistoryItem[]) => void): () => void {
  if (typeof window === "undefined") return () => {};
  
  const handler = () => {
    callback(getHistoryItems());
  };
  
  window.addEventListener(EVENT_NAME, handler);
  window.addEventListener("storage", handler);
  
  return () => {
    window.removeEventListener(EVENT_NAME, handler);
    window.removeEventListener("storage", handler);
  };
}
